Vision doc
SpokaneTech/SpokaneTech_Py pull request #86
Opened 2024-03-31 22:50 UTC by davidslusser

## Pull Request

**Description:**
closes #85; adding vision doc to explain the reason for and direction of the project 

**Checklist:**
- [x] All tests pass.
- [x] Code follows the project's coding standards.
- [x] Documentation has been updated.

2024-04-01 03:03 UTC, joeriddles requested changes
This is great! Mostly of the comments are spelling changes. Moving this to the docs repo would be awesome.

2024-04-01 03:03 UTC, joeriddles commented on .github/VISION.md
> +The Spokane Tech project was started mostly by members of the Spokane Python User Group (SPUG), so natually the first version of the website is based on python. In the future the project will be re-c
```suggestion
The Spokane Tech project was started mostly by members of the Spokane Python User Group (SPUG), so naturally the first version of the website is based on Python. In the future the project may be re-created in other languages/frameworks/etc. (such as Go or Rust) as member interest dictates. This is intended to foster growth, knowledge sharing, and exposure to different tech stacks and methodologies.
```

2024-04-01 03:03 UTC, joeriddles commented on .github/VISION.md
> +- Go to the site and explore. It's live at https://www.spokanetech.org
```suggestion
- Go to the site and explore. It's live at https://spokanetech.org
```

2024-04-01 03:03 UTC, joeriddles commented on .github/VISION.md
> +- clone the repo to you machine and run locally, explore the code, break things, fix things, have fun. Step by step instructions are in the CONTRIBUTION doc.
```suggestion
- Clone the repo to you machine and run locally, explore the code, break things, fix things, have fun. Step by step instructions are in the [CONTRIBUTING](https://spokanetech.github.io/SpokaneTech_Py/CONTRIBUTING/) doc.
```

2024-04-02 03:31 UTC, davidslusser commented on .github/VISION.md
> +# About the Spokane Tech Project
sure

2024-04-02 03:32 UTC, davidslusser commented on .github/VISION.md
> +## What is?
I decided to just remove the subtitle

2024-04-02 03:38 UTC, davidslusser commented
doc moved; spell checked working this time

2024-04-02 03:53 UTC, joeriddles commented
Can you add the doc to `mkdocs.yml` so it appears in the docs site?

2024-04-02 05:19 UTC, davidslusser commented
> Can you add the doc to `mkdocs.yml` so it appears in the docs site? Sorry I forgot to mention that in the original review.

done

2024-04-02 05:21 UTC, joeriddles approved these changes

2024-04-03 02:38 UTC, merged